{% set name = "leafmap" %}
{% set version = "0.40.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f508cda5f9b35d7636191a6348ff1bf8e9697379353f0b84766b7e46f19775c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - anywidget
    - bqplot
    - colour
    - folium
    - gdown
    - geojson
    - geopandas
    - ipyevents
    - ipyfilechooser
    - ipyleaflet
    - ipyvuetify
    - ipywidgets
    - ipysheet
    - jupyterlab
    # - maplibre
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - pmtiles
    - pyarrow
    - pycrs
    - pyshp
    - pystac-client
    - python-box
    - scooby
    - whiteboxgui
    - xyzservices
    - python-duckdb

test:
  imports:
    - leafmap
  # commands:
  #  - pip check
  requires:
    - pip

about:
  home: https://github.com/opengeos/leafmap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  description: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  doc_url: https://leafmap.org
  dev_url: https://github.com/opengeos/leafmap

extra:
  recipe-maintainers:
    - giswqs
