{% set name = "leafmap" %}
{% set version = "0.29.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7353fc060beb8d4898e2387fd48b9218a6b550bfd5f263e2e3f6ffaa023449de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - bqplot
    - colour
    - folium
    - gdown
    - geojson
    - ipyevents
    - ipyfilechooser
    - ipyleaflet
    - ipywidgets
    - ipysheet
    - jupyterlab
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - pycrs
    - pyshp
    - pystac-client
    - python-box
    - scooby
    - whiteboxgui
    - xyzservices
    - python-duckdb

test:
  imports:
    - leafmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/leafmap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  description: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  doc_url: https://leafmap.org
  dev_url: https://github.com/giswqs/leafmap

extra:
  recipe-maintainers:
    - giswqs
