{% set name = "leafmap" %}
{% set version = "0.38.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc0aca3511d1a23c8b89429b2ccc51bbba229c4cc5c15699a20652fa7701e78f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - anywidget
    - bqplot
    - colour
    - folium
    - gdown
    - geojson
    - geopandas
    - ipyevents
    - ipyfilechooser
    - ipyleaflet
    - ipyvuetify
    - ipywidgets
    - ipysheet
    - jupyterlab
    # - maplibre
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - pmtiles
    - pyarrow
    - pycrs
    - pyshp
    - pystac-client
    - python-box
    - scooby
    - whiteboxgui
    - xyzservices
    - python-duckdb

test:
  imports:
    - leafmap
  # commands:
  #  - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/leafmap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  description: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  doc_url: https://leafmap.org
  dev_url: https://github.com/giswqs/leafmap

extra:
  recipe-maintainers:
    - giswqs
