{% set name = "leafmap" %}
{% set version = "0.52.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9df12517e6e7e0cab122119e6bea6b2c4a99b6d9fc1ea60b2532a3ec7edad1d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - anywidget
    - bqplot
    - folium
    - gdown
    - geojson
    - geopandas
    - h5netcdf
    - h5py
    - ipyevents
    - ipyfilechooser
    - ipyleaflet
    - ipyvuetify
    - ipywidgets
    - ipysheet
    - jupyterlab
    - localtileserver
    - maplibre
    - matplotlib-base
    - numpy
    - opera-utils
    - pandas
    - plotly
    - pmtiles
    - pyarrow
    - pycrs
    - pystac-client
    - python-box
    - rioxarray
    - scooby
    - whiteboxgui
    - xyzservices
    - python-duckdb

test:
  imports:
    - leafmap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/leafmap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  description: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  doc_url: https://leafmap.org
  dev_url: https://github.com/opengeos/leafmap

extra:
  recipe-maintainers:
    - giswqs
