{% set name = "leafmap" %}
{% set version = "0.36.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8af4f143c4d800a39b19b997052bf380a3e17395b189776a82778469f66cd5ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - anywidget
    - bqplot
    - colour
    - folium
    - gdown
    - geojson
    - ipyevents
    - ipyfilechooser
    - ipyleaflet
    - ipyvuetify
    - ipywidgets
    - ipysheet
    - jupyterlab
    - matplotlib-base
    - numpy <2.0.0
    - pandas
    - plotly
    - pycrs
    - pyshp
    - pystac-client
    - python-box
    - scooby
    - whiteboxgui
    - xyzservices
    - python-duckdb

test:
  imports:
    - leafmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/leafmap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  description: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  doc_url: https://leafmap.org
  dev_url: https://github.com/giswqs/leafmap

extra:
  recipe-maintainers:
    - giswqs
