{% set name = "leafmap" %}
{% set version = "0.43.5" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58681a2cbf34c09b6b29f21a50ae05ba5ea0cfb111e7af4f253c049f4e3f6b87

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - anywidget
    - bqplot
    - colour
    - folium
    - gdown
    - geojson
    - geopandas
    - ipyevents
    - ipyfilechooser
    - ipyleaflet
    - ipyvuetify
    - ipywidgets
    - ipysheet
    - jupyterlab
    # - maplibre
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - pmtiles
    - pyarrow
    - pycrs
    - pyshp
    - pystac-client
    - python-box
    - scooby
    - whiteboxgui
    - xyzservices
    - python-duckdb

test:
  imports:
    - leafmap
  commands:
   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/leafmap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  description: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  doc_url: https://leafmap.org
  dev_url: https://github.com/opengeos/leafmap

extra:
  recipe-maintainers:
    - giswqs
