{% set name = "leafmap" %}
{% set version = "0.27.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0ef5385484c518cfd6cfc8bb1d3aa985fd71fd5e28a07993f59445f018b9f52

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - bqplot
    - colour
    - folium
    - gdown
    - geojson
    - ipyevents
    - ipyfilechooser
    - ipyleaflet
    - ipywidgets
    - ipysheet
    - jupyterlab <4.0
    - matplotlib-base
    - numpy
    - pandas
    - pycrs
    - pyshp
    - pystac-client
    - python-box
    - scooby
    - whiteboxgui
    - xyzservices

test:
  imports:
    - leafmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/leafmap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for geospatial analysis and interactive mapping in a Jupyter environment
  doc_url: https://leafmap.org
  dev_url: https://github.com/giswqs/leafmap

extra:
  recipe-maintainers:
    - giswqs
